//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bludata.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        public string Cpf { get; set; }
        public string Nome { get; set; }
        public string Rg { get; set; }
        public string Uf { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Telefone { get; set; }
    }
}
